### ISSUE TITLE
the buildout for a generated basic dexterity add'on package pulls in plone.app.event 2.0.X

### ISSUE THREAD

**Issue by fredvd** [plone/bobtemplates.plone#106]
When I generate a dexterity add'on using bobtemplates.plone 1.0b1 the vanille buildout pulls in plone.app.event 2.X (for Plone 5) which breaks the buildout. 

plone.app.event is pulled in by plone.app.contenttypes, and there I've lost which package in the current setup is pulling in p.a.contenttypes (if that's the cause). 

Quick fix is adding pins for plone.app.event and other packages that plone.app.contenttypes needs that work for Plone 4, but p.a.event and it's dependers shouldn't be in here at all.

```
# for plone.app.contenttypes 1.1b5
plone.app.contenttypes = 1.1b5
plone.app.event = 1.1.5
icalendar = 3.9.0
plone.event = 1.1
plone.formwidget.datetime = 1.1
plone.formwidget.recurrence = 1.2.5
```

**Comment by tisto** [comment]
I think we still have a problem with our travis setup. Otherwise problems like that should have been caught by the ci.

**Comment by jensens** [comment]
i think current master is clean at this point
