### ISSUE TITLE
Feature: Use lingua instead of i18ndude?

### ISSUE THREAD

**Issue by jensens** [plone/bobtemplates.plone#108]
See discussion at collective/i18ndude#22

**Comment by tisto** [comment]
I would like @vincentfretin to confirm that decision. I think it is confusing to create an issue here before we reached an agreement on the referenced issue...

**Comment by jensens** [comment]
I agree, that is the reason why I added a "?" to the headline. Also the discussion was about ``bobtemplates.plone``. So this issue will help us to keep the loose ends together.

**Comment by vincentfretin** [comment]
I'll do some tests again with latest lingua and msgmerge to see if that's ok.

**Comment by jensens** [comment]
:+1: I'am very interested, please report back.

**Comment by vincentfretin** [comment]
We now have zcml extraction in i18ndude. i18ndude works great, I won't spend time to test lingua to see if all plone use cases are covered by it.
Just to inform you, msgmerge is an external dependency, you need to do apt-get install gettext on Debian/Ubuntu. I don't know what you have to do on Mac or Windows.
If someone want to use lingua on their projects, please do. If there are several persons using it and it actually has advantages over i18ndude, we can ask again the question to promote lingua as a default.
