### ISSUE TITLE
Change the order of 'i18n:register Translations' in configure.zcml to allow overwrite translations of plone domain

### ISSUE THREAD

**Issue by idgserpro** [plone/bobtemplates.plone#110]
If I use the bobtemplates.plone, add the Products.CMFPlone as dependency in setup.py, can't overwrite translations of plone domain, following [this documentation](http://docs.plone.org/develop/plone/i18n/internationalisation.html#overriding-translations).

This's because [includeDependencies](https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone_addon/src/%2Bpackage.namespace%2B/%2Bpackage.name%2B/configure.zcml.bob#L11), will load the locales of plone.app.locales (since it is dependency of Products.CMFPlone) before the [locales of my product](https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone_addon/src/%2Bpackage.namespace%2B/%2Bpackage.name%2B/configure.zcml.bob#L13).

Calling i18n:registerTranslations before includeDependencies works.

**Comment by pbauer** [comment]
@idgserpro please create a pull-request to that effect

**Comment by idgserpro** [comment]
@pbauer I don't have Plone Contributor Agreement.
