### ISSUE TITLE
bootstrap of new package fails with unicode error

### ISSUE THREAD

**Issue by jensens** [plone/bobtemplates.plone#114]
Using bobtemplates.plone master:

```
jensens@minime:/home/workspacejensens$ ./bobtemplates.plone/bin/mrbob -O jensens.testaddon bobtemplates:plone_addon

Welcome to mr.bob interactive mode. Before we generate directory structure, some questions need to be answered.

Answer with a question mark to display help.
Values in square brackets at the end of the questions show the default value if there is no answer.


--> What kind of package would you like to create? Choose between 'Basic', 'Dexterity', and 'Theme'. [Basic]: 

--> Author's name [Jens W. Klein]: 

--> Author's email [jk@kleinundpartner.at]: 

--> Author's github username: jensens

--> Package description [An add-on for Plone]: 

--> Plone version [4.3.7]: 5.0.2


Generated file structure at /home/workspacejensens/jensens.testaddon

jensens@minime:/home/workspacejensens/jensens.testaddon$ python --version
Python 2.7.6

jensens@minime:/home/workspacejensens/jensens.testaddon$ python bootstrap-buildout.py 
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-19.2.zip
Extracting in /tmp/tmpV97vf3
Now working in /tmp/tmpV97vf3/setuptools-19.2
Building a Setuptools egg in /tmp/tmp5IAQ0I
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    exec(init_file.read(), command_ns)
  File "<string>", line 11, in <module>
  File "/tmp/tmpV97vf3/setuptools-19.2/setuptools/__init__.py", line 12, in <module>
    from setuptools.extension import Extension
  File "/tmp/tmpV97vf3/setuptools-19.2/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "/tmp/tmpV97vf3/setuptools-19.2/setuptools/dist.py", line 19, in <module>
    import pkg_resources
  File "/tmp/tmpV97vf3/setuptools-19.2/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/tmp/tmpV97vf3/setuptools-19.2/pkg_resources/__init__.py", line 3124, in _call_aside
    f(*args, **kwargs)
  File "/tmp/tmpV97vf3/setuptools-19.2/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/tmp/tmpV97vf3/setuptools-19.2/pkg_resources/__init__.py", line 652, in _build_master
    ws = cls()
  File "/tmp/tmpV97vf3/setuptools-19.2/pkg_resources/__init__.py", line 645, in __init__
    self.add_entry(entry)
  File "/tmp/tmpV97vf3/setuptools-19.2/pkg_resources/__init__.py", line 701, in add_entry
    for dist in find_distributions(entry, True):
  File "/tmp/tmpV97vf3/setuptools-19.2/pkg_resources/__init__.py", line 2139, in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/tmp/tmpV97vf3/setuptools-19.2/pkg_resources/__init__.py", line 2521, in from_location
    py_version=py_version, platform=platform, **kw
  File "/tmp/tmpV97vf3/setuptools-19.2/pkg_resources/__init__.py", line 2835, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/tmp/tmpV97vf3/setuptools-19.2/pkg_resources/__init__.py", line 2486, in _version_from_file
    line = next(iter(version_lines), '')
  File "/tmp/tmpV97vf3/setuptools-19.2/pkg_resources/__init__.py", line 2654, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/tmp/tmpV97vf3/setuptools-19.2/pkg_resources/__init__.py", line 2030, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/tmp/tmpV97vf3/setuptools-19.2/pkg_resources/__init__.py", line 2025, in get_metadata
    metadata = f.read()
  File "/usr/lib/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb6 in position 147: invalid start byte
/tmp/tmp5IAQ0I/setuptools-19.2-py2.7.egg
Traceback (most recent call last):
  File "bootstrap-buildout.py", line 98, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 173, in use_setuptools
  File "<string>", line 124, in _do_download
  File "<string>", line 71, in _build_egg
IOError: Could not build the egg.
```

**Comment by jensens** [comment]
using a more modern approach with virtualenv + pip works:

        jensens@minime:/home/workspacejensens/jensens.testaddon$ virtualenv .
        New python executable in ./bin/python
        Installing setuptools, pip...done.
        
        jensens@minime:/home/workspacejensens/jensens.testaddon$ ./pip install -U zc.buildout setuptools pip 
        bash: ./pip: No such file or directory
        jensens@minime:/home/workspacejensens/jensens.testaddon$ ./bin/pip install -U zc.buildout setuptools pip 
        Downloading/unpacking zc.buildout
          Downloading zc.buildout-2.5.0-py2.py3-none-any.whl (261kB): 261kB downloaded
        Downloading/unpacking setuptools from https://pypi.python.org/packages/3.5/s/setuptools/setuptools-19.2-py2.py3-none-any.whl#md5=7bdac510b6bc1675a2a149eb3f81af77
          Downloading setuptools-19.2-py2.py3-none-any.whl (463kB): 463kB downloaded
        Downloading/unpacking pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-7.1.2-py2.py3-none-any.whl#md5=5ff9fec0be479e4e36df467556deed4d
          Downloading pip-7.1.2-py2.py3-none-any.whl (1.1MB): 1.1MB downloaded
        Installing collected packages: zc.buildout, setuptools, pip
          Found existing installation: setuptools 2.2
            Uninstalling setuptools:
              Successfully uninstalled setuptools
          Found existing installation: pip 1.5.4
            Uninstalling pip:
              Successfully uninstalled pip
        Successfully installed zc.buildout setuptools pip
        Cleaning up...
    jensens@minime:/home/workspacejensens/jensens.testaddon$ ./bin/buildout 
    Creating directory '/home/workspacejensens/jensens.testaddon/parts'.
    Creating directory '/home/workspacejensens/jensens.testaddon/develop-eggs'.
    Upgraded:
      zc.buildout version 2.4.1,
      setuptools version 18.1;
    restarting.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/buildout'.
    Develop: '/home/workspacejensens/jensens.testaddon/.'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    Unused options for buildout: 'unzip'.
    Installing _mr.developer.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/develop'.
    Installing instance.
    /home/jensens/.buildout/shared-eggs/setuptools-18.1-py2.7.egg/pkg_resources/__init__.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
      stacklevel=1,
    Generated script '/home/workspacejensens/jensens.testaddon/bin/instance'.
    Generated interpreter '/home/workspacejensens/jensens.testaddon/parts/instance/bin/interpreter'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/pilconvert.py'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/pilprint.py'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/pildriver.py'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/pilfont.py'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/pilfile.py'.
    Installing test.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/test'.
    Installing code-analysis.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/flake8'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/check-manifest'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/code-analysis'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/code-analysis-csslint'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/code-analysis-check-manifest'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/code-analysis-clean-lines'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/code-analysis-flake8'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/code-analysis-find-untranslated'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/code-analysis-jscs'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/code-analysis-jshint'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/code-analysis-zptlint'.
    Unable to create git pre-commit hook, this does not seem to be a git repository.
    Installing releaser.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/fullrelease'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/postrelease'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/lasttagdiff'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/prerelease'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/release'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/longtest'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/lasttaglog'.
    Installing i18ndude.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/i18ndude'.
    Installing omelette.
    Installing robot.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/robot-server'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/robot-debug'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/ride'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/robot'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/libdoc'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/pybabel'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/pybot'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/pilconvert.py'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/pilprint.py'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/pildriver.py'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/pilfont.py'.
    Generated script '/home/workspacejensens/jensens.testaddon/bin/pilfile.py'.

**Comment by jensens** [comment]
I propose to kick out ``bootstrap-buildout.py`` completly - it just brings in trouble - and add some ``bootstrap.sh`` like::

    #!/bin/sh
    rm -r ./lib ./include ./local ./bin
    virtualenv --clear .
    ./bin/pip install --upgrade pip setuptools zc.buildout
    ./bin/buildout

**Comment by thet** [comment]
+1 for kicking out bootstrap-buildout.py.

Although I cannot reproduce the error above. But installing zc.buildout via pip is cleaner, easier and less frightening for non-plone people.

**Comment by gforcada** [comment]
If PLIP'ed and documentation gets updated I would give a +1 as well, until then I would take a more conservative approach, as to not confuse people...

**Comment by tisto** [comment]
It does not really help if we bring up this issue via three different channels...if we reached an agreement as a community, we can amend bobtemplates.plone, before that we should always be conservative regarding to changes.

**Comment by jensens** [comment]
someone already changed this in a different content, so this is no longer an issue.
