### ISSUE TITLE
No development environment created on Windows

### ISSUE THREAD

**Issue by Niedes** [plone/bobtemplates.plone#120]
On Windows (7, 64bit to be precise) the directory 'bla.nenn' is empty after running
`bin/mrbob.exe -O bla.nenn bobtemplates:plone_addon`
altaough it says
`Generated file structure at e:\mrbobtests\bla.nenn`
I tried both: installing bobtemplates.plone via pip and also
installing bobtemplates.plone via buildout including
`find-links =
    ${buildout:directory}/pywin32-220.win-amd64-py2.7.exe
...
eggs =
    ...
    pywin32
`

**Comment by jensens** [comment]
this is mainly because in ``hooks.py`` at several places the seperator for paths is ``/`` but should be ``os.sep``.

**Comment by jensens** [comment]
addressed in #177
