### ISSUE TITLE
plone_addon Theme is a hidden profile by default?

### ISSUE THREAD

**Issue by fredvd** [plone/bobtemplates.plone#143]
What's the rationale behind making the add'on hidden in the add'on screen when scaffolding a new Theme package?  How should someone who created the package then install the theme in Plone, only by linking to it as a dependency from a policy package? 

(configure.zcml has a utility to .setuphandlers.HiddenProfiles that adds an INonInstallable marker)

**Comment by gforcada** [comment]
If that's really the rationale, a warning should be printed, or added on a generated file, so that the user knows that an extra step is needed.

**Comment by gforcada** [comment]
Looking at the code, it either has been fixed after you reported or there's still a bug, because right now it should only hide the uninstall profile only.

Please reopen if install profile is still not shown.
