### ISSUE TITLE
Use plone:static instead of browser:resourceDirectory for resources

### ISSUE THREAD

**Issue by pbauer** [plone/bobtemplates.plone#159]
Using plone:static instead of browser:resourceDirectory would allow overwriting the resources through the web. 
```xml
<plone:static
    name="{{{ package.dottedname }}}"
    type="plone"
    directory="static"
    />
```
instead of 
```xml
<browser:resourceDirectory
    name="{{{ package.dottedname }}}"
    directory="static"
    />
```
Are there any drawbacks?

**Comment by davilima6** [comment]
@pbauer, the [docs mentions](http://docs.plone.org/adapt-and-extend/theming/resourceregistry.html#the-plone-traversal-namespace) less caching for `++plone++` resources but it's not clear where this happens:

> When providing static resources (JavaScript/Less/CSS) for Plone 5's resource registry, use plone.resource based resources instead of Zope's browser resources. The latter are cached heavily and you won't get your changes compiled into bundles, even after Zope restarts.

I thought maybe `++resources++` had a volatile cache similar to the one in Portal Transforms, but I guess that wouldn't hold after a restart. Not sure either about whether and how much `p.a.caching` fixes this at a later point. If it does, I'd like to know if there would be any drawbacks in deprecating the other namespaces so we can minimize noise.
