### ISSUE TITLE
Documentation link is broken.

### ISSUE THREAD

**Issue by pe82** [plone/bobtemplates.plone#161]
Documentation link is broken.

**Comment by gforcada** [comment]
@pe82 thanks for reporting, would you mind providing *where* did you see the link that is broken? That would make it easier to fix it.

**Comment by pe82** [comment]
Main page: https://github.com/plone/bobtemplates.plone

**Comment by gforcada** [comment]
@pe82 I just fixed it, thanks for reporting!
