### ISSUE TITLE
Created reST syntax is almost never valid

### ISSUE THREAD

**Issue by svx** [plone/bobtemplates.plone#170]
Currently if you create a add-on with bobtemplates the reST syntax of the README.rst and of the docs.index.rst will almost never valid.

Since we do not know the length of the add-on name we currently use for the README for example

``` rst
==============================================================================
{{{ package.dottedname }}}
==============================================================================
```

This will only produce valid reST if the name of the package will as long as the amount of _=_ signs

For index we have currently:

``` rst
====================
{{{ package.dottedname }}}
====================
```

This means if I have a add-on called for example:

**collective.mysuperawesome**

bobtemplates will create non valid reST for the README and for docs/index

Results of this:
- tests on documentation will always fail
- running sphinx-build will give you errors/warnings or will fail, depending in which mode you run it

**Comment by gforcada** [comment]
#172 fixes that just to reference one to the other.

**Comment by gforcada** [comment]
Fixed
