### ISSUE TITLE
Classifiers in package itself are incomplete

### ISSUE THREAD

**Issue by tomgross** [plone/bobtemplates.plone#186]
The package does not specify the Python versions it supports.
Maybe run pyroma?

**Comment by MrTango** [comment]
zest releaser has pyroma included, shouldn't be that enough?

**Comment by tomgross** [comment]
Fixed with https://github.com/plone/bobtemplates.plone/pull/206

**Comment by MrTango** [comment]
@loechel can you please check if this is fixed now?

**Comment by loechel** [comment]
fixed with https://github.com/plone/bobtemplates.plone/commit/f5991a5537a4af650c3b4ff2f1188171b7e3d3e3
