### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by tomgross** [plone/bobtemplates.plone#187]
The package runs on Python 3. The only issues I found are
- [ ] #186 and
- [ ] byte strings are put into the templates with the b'' prefix. This might be an issue of mr.bob.

**Comment by tomgross** [comment]
Some work is done here https://github.com/plone/bobtemplates.plone/pull/206

**Comment by gforcada** [comment]
mr.bob claims support for python 3 (up to 3.4) on its pypi page.

**Comment by loechel** [comment]
#206 prove that it would work on all relevant Python 3 versions.
We have to see if that also applies to the 3.0 branch. #216 make it testable, but the test from #206 have not been moved.

**Comment by jensens** [comment]
closed with #344
