### ISSUE TITLE
Remove 'sudo: false' from .travis.yml

### ISSUE THREAD

**Issue by idgserpro** [plone/bobtemplates.plone#193]
When we run travis with [sudo: false](https://github.com/plone/bobtemplates.plone/blob/f8c93c1a508b2e332aa9312dfd18e941993acb91/bobtemplates/plone_addon/.travis.yml.bob#L2), we receive the message:

```
This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.

If you require sudo, add 'sudo: required' to your .travis.yml

See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
```

It was checking and it seems that the infrastructure when running without 'sudo: false' is better. This can be seen in:

https://docs.travis-ci.com/user/ci-environment/

It has more memory and the file system is ext4. Besides, it's default of Travis.

'sudo: false' was added in @jensens 's [commit](https://github.com/plone/bobtemplates.plone/commit/550ce0316d396a1c6d39e4ca1f5a1a28ac831a87).

**Comment by mauritsvanrees** [comment]
We use `sudo: false` because this allows to cache things, most importantly the downloaded and installed eggs. This speeds up next builds a lot.
See the docs about the [container based infrastructure](https://docs.travis-ci.com/user/migrating-from-legacy/#Caching-available-for-open-source-projects) which is used when you use `sudo: false`.

The [page you point to](https://docs.travis-ci.com/user/ci-environment/) has a table that says container base (sudo false) is the default since 2015.

**Comment by idgserpro** [comment]
> We use sudo: false because this allows to cache things

@mauritsvanrees  the cache works with ```sudo: required``` :smile: 

I made [this commit](https://github.com/collective/collective.nitf/commit/a1a5fc42e703757e5179aa34a09e33e409be44a6) and as expected, the eggs were [downloaded](https://travis-ci.org/collective/collective.nitf/jobs/198887881#L1282) since it had never been run on that infrastructure.

Then I did [this commit](https://github.com/collective/collective.nitf/commit/af6ec0962ed6aa510d4175c4cd9683d45f270546) to test the cache and it [did not download](https://travis-ci.org/collective/collective.nitf/jobs/198892687#L1279) again, ie the cache worked.

> The page you point to has a table that says container base (sudo false) is the default since 2015.

The documentation must be outdated. I made [this commit](https://github.com/collective/collective.nitf/commit/c01b4cf536f6b914d6dddd0b6d62570e8b83b591) and [did not receive the message](): ```This job is running on container-based infrastructure...``` That is, it is using ```sudo: required```.

**Comment by idgserpro** [comment]
> The documentation must be outdated. I made this commit and did not receive the message: This job is running on container-based infrastructure... That is, it is using sudo: required.

@mauritsvanrees the repository that I used to test must have been enabled before 2015. Therefore it's using ```sudo: required``` as default :unamused: 

Anyway, the cache works with ```sudo: required```

**Comment by mauritsvanrees** [comment]
Ah, they must have changed how this works then. Or the docs were always wrong. So now we can always use the cache: good!

Then we can debate what the best default is for Plone projects. The default as I see it in the table on https://docs.travis-ci.com/user/ci-environment/ is container based, so `sudo: false`. If Travis makes that the default, we should probably do the same.

In that table you can see that container based starts up faster: 1-6 seconds versus 20-52 seconds.

I would say we stick to their default. Individual projects that *really* need more, or indeed need actual `sudo` commands, can change it themselves.

**Comment by idgserpro** [comment]
@mauritsvanrees one more reason to remove `sudo: false`. It's now deprecated. See:

https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

**Comment by idgserpro** [comment]
@mauritsvanrees can you please reopen this issue? `sudo: false` has not yet been removed.

**Comment by mauritsvanrees** [comment]
Reopened.
