### ISSUE TITLE
flake8 version pin (3.0.4) causes version conflict for pycodestyle

### ISSUE THREAD

**Issue by fulv** [plone/bobtemplates.plone#194]
Currently, `flake8` is pinned to 3.0.4.  This version of `flake8` restricts the allowable version of `pycodestyle` to `<2.1.0,>=2.0.0`.  But since `pycodestyle` is not pinned, we get the latest (currently 2.3.1), and then a version conflict:

```
Version and requirements information containing pycodestyle:
  Requirement of flake8-todo: pycodestyle<3.0.0,>=2.0.0
  Requirement of flake8>=2.4.0: pycodestyle<2.1.0,>=2.0.0
While:
  Installing.
  Getting section code-analysis.
  Initializing section code-analysis.
  Installing recipe plone.recipe.codeanalysis[recommended].
Error: There is a version conflict.
We already have: pycodestyle 2.3.1
but flake8 3.0.4 requires 'pycodestyle<2.1.0,>=2.0.0'.
```

I have tried to change the `flake8` pin to the latest (`flake8 = 3.3.0`), and this allows buildout to complete.  Alternatively, we could pin `pycodestyle` to a version allowed by `flake8 3.0.4` (`pycodestyle = 2.0.0`).

Thoughts?

**Comment by gforcada** [comment]
I would pin a newer version. Latest is always greatest, right? 😃

**Comment by fulv** [comment]
Ok, will do.

**Comment by idgserpro** [comment]
You fixed this but a new release of bobtemplates.plone wasn't made: I got the error from a freshly created package from bobtemplates.plone, searched on google and got that I needed to pin flake8 like @fulv suggested.

Any new release on the horizon?

**Comment by gforcada** [comment]
@idgserpro I was about to make a 2.0a1 release but I see that only @pbauer and @tisto are pypi maintainers... would you (@tisto @pbauer) either make the release or grant ``plone`` user on pypi the rights to do so?
