### ISSUE TITLE
self.installer variable is not used

### ISSUE THREAD

**Issue by idgserpro** [plone/bobtemplates.plone#215]
`self.installer` is defined in tests template but is not used anywhere.

https://github.com/plone/bobtemplates.plone/blob/b1c753e0614914547dc0351196885fcaf23de012/bobtemplates/plone_theme_package/src/%2Bpackage.namespace%2B/%2Bpackage.name%2B/tests/test_%2Bpackage.dexterity_type_name_lower%2B.py.bob#L22

**Comment by MrTango** [comment]
thx, I'll removed that
