### ISSUE TITLE
adding content types with bobtemplates.plone

### ISSUE THREAD

**Issue by ksuess** [plone/bobtemplates.plone#219]
Adding content types with bobtemplates is a wonderful extension. I have some remarks.

Maybe the permission could be set to an already existing one. So that an object of the type could just be added by editors.
  
  
  <property name="add_permission">cmf.AddPortalContent</property>

i18n:domain="example.myaddon" nicht "plone"

**Comment by MrTango** [comment]
thx for the hint, I'll fix the domain.
But regarding the permission, this shou lalready work as exspected.
The new permission has the same rolemap as the AdPortalContent:

```
    <permission name="{0}: Add {1}" acquire="True">
      <role name="Manager"/>
      <role name="Site Administrator"/>
      <role name="Owner"/>
      <role name="Contributor"/>
    </permission>
```

So editors shouls have the right permission by default, but one could adjust it, as she wants.

**Comment by MrTango** [comment]
by edited you mean Added as "Contributor" right?

**Comment by MrTango** [comment]
domain is fixed in: https://github.com/plone/bobtemplates.plone/commit/0d534f358eff29ea83f11de4750d12d0df3fc986
I also adjusted the Add content type test, to use the Contributor role, so that we are sure that this works.
