### ISSUE TITLE
New travis setup broken again?

### ISSUE THREAD

**Issue by pbauer** [plone/bobtemplates.plone#228]
I changed the travis setup of https://github.com/collective/collective.fieldedit to the new one by @hvelarde and @jensens and got a very weird error. When pip should install `setuptools 33.1.1` as stated in `requirements.txt` it installed `setuptools 36.0.1` instead. 

```
$ pip install -r requirements.txt
Collecting zc.buildout==2.8.0 (from -r requirements.txt (line 1))
  Using cached zc.buildout-2.8.0-py2.py3-none-any.whl
Collecting setuptools==33.1.1 (from -r requirements.txt (line 2))
  Using cached setuptools-33.1.1-py2.py3-none-any.whl
Installing collected packages: setuptools, zc.buildout
  Found existing installation: setuptools 36.3.0
    Uninstalling setuptools-36.3.0:
      Successfully uninstalled setuptools-36.3.0
Successfully installed setuptools-36.0.1 zc.buildout-2.8.0
```
See https://travis-ci.org/collective/collective.fieldedit/builds/287923249 for the full log.

**Comment by jensens** [comment]
weird.

**Comment by jensens** [comment]
Ok, looks like we now need a ``virtualenv`` on Travis. This wasn't necessary for the past and I have no idea what changed, on Travis base setup. 

See https://github.com/collective/collective.fieldedit/commit/296f8b6a848a55ea4af4a2a34c95de896dce0fb8

**Comment by pbauer** [comment]
That worked. Thanks.
