### ISSUE TITLE
Different roles in tests for install and uninstall.

### ISSUE THREAD

**Issue by jensens** [plone/bobtemplates.plone#235]
By default the ``test_setup.py.bob`` defines two tests ``TestSetup`` and ``TestUninstall``. 

In ``TestSetup`` everything was already executed because this happens in the test layers. The user there has the ``Manager`` role. The test just checks if everything is there.

In ``TestUninstall`` the uninstall is executed in the test with default roles of the test, that is the ``Member`` role. 
In my opinion, this is wrong. Before uninstall, the Manager role has to be adopted.

I stumbled across this because I wanted to remove an ``OFS.folder.Folder`` in setuphandlers ``uninstall`` I created at ``post_install``.

I propose to add a ``setRoles(self.portal, TEST_USER_ID, ['Manager'])`` to ``TestUninstall`` prior to the ``uninstallProducts`` call.

Opinions?

**Comment by mauritsvanrees** [comment]
I would expect that the test user only has the Member role. If a test `setUp` method temporarily needs the Manager role, which seems logical when calling uninstall, that is fine. But at the end of `setUp` we should return back to normal: just the Member role.

**Comment by jensens** [comment]
@mauritsvanrees good point. I addressed this in cb9b65e25709e345bdf7378748a9feac506290f9
