### ISSUE TITLE
Move tests out of package directory

### ISSUE THREAD

**Issue by thet** [plone/bobtemplates.plone#242]
In icalendar, there is a PR ( https://github.com/collective/icalendar/pull/250 ) which moves the tests out of the package directory.
I think it's not a good idea to not have the tests always installed in production environments, where they are dead code.
If it doesn't have any serious downsides we should consider this as best practice and do it for bobtemplates.plone.

Two downsides I can come up with now are:
- For installed packages, tests cannot be run anymore. This might be a blocker.
- Tests, which also serve as documentation, are not available via omelette anymore.

Any thoughts?

**Comment by jdufresne** [comment]
> I think it's not a good idea to not have the tests always installed in production environments, where they are dead code.

Just looking for clarification. Is this double negative a typo?

**Comment by jdufresne** [comment]
I see the following article in the "Discussion on Plone Best Practices" documentation.

https://plone-best-practices-discussion.readthedocs.io/en/latest/package_layout/tests_folder.html

**Comment by MrTango** [comment]
The best practices are just drafts and need more comments and discussions.
We need to find a common sense here before we start changing the ways things are.
I get the point that tests are not for production packages.
But then we have to solve the problems @thet mentioned or decide to live with it.
@thet maybe we should discuss this in the forum?

**Comment by pbauer** [comment]
I'm 👎 as well. Dead code on production does not worry me, also egg-sizes are a non-issue. I often check the tests if the docs are bad (i.e. often) and not having them would be annoying.

**Comment by MrTango** [comment]
I closes this issue here.
We should continue the discussion in the forum if needed.
