### ISSUE TITLE
pip installs older version

### ISSUE THREAD

**Issue by meshde** [plone/bobtemplates.plone#251]
Running `pip install bobtemplates.plone` installs version 2.0, while most of the documentation available is that of version 3.0.3a

I installed the package and tried following the steps as shown [here](https://docs.plone.org/develop/addons/bobtemplates.plone/bobtemplates.plone/docs/) to create an addon:
`mrbob bobtemplates.plone:addon -O collective.foo`

But this gives an error as the command to do the same in version 2.0 was:
`mrbob bobtemplates:plone_addon -O collective.foo`

**Comment by MrTango** [comment]
Thats normal, the version 3.0.0 was alpha or beta, so pip choose the stable version.
The 3.0.0 final is released now, so that should be fine now.
