### ISSUE TITLE
No status-codes return value from code-analysis in tox tests

### ISSUE THREAD

**Issue by tmassman** [plone/bobtemplates.plone#261]
The tox tests check for the return value of the code-analysis output, but the current configuration disables those in the `buildout.cfg.bob` template. It should be `False` for development and `True`  for CI, but the tox configuration seems to be missing something. Example test: https://travis-ci.org/plone/bobtemplates.plone/jobs/346936640#L1701

**Comment by MrTango** [comment]
yes, currently it is deactivated because in local environment you usually want to see problems but not necessary block the commit. We can add a ci.cfg wich enable this for travis.

**Comment by MrTango** [comment]
https://github.com/plone/bobtemplates.plone/pull/268

**Comment by loechel** [comment]
so those are different things, and we should handle that seperately.

A tox run should always report code validations and fail on that. So local and on CI.

A pre-commit hook that aborts commit is something different. I actually don't like that code-analysis actively installes a pre-commit hook. My preference is to deprecate code-analysis and do full linting via tox (see http://plone-best-practices-discussion.readthedocs.io/en/latest/tox/standard_sections.html#flake8) 

A ci.cfg is also not necessary to do so, as you could use cli params in tox.ini or .travis.yml

which would look like for tox:
```ini
[tox]
envlist = 
    ...
    code-analysis
...
[code-analysis]
commands =
    ...
    {envbindir}/buildout -c {toxinidir}/{env:version_file} buildout:directory={toxinidir} code-analsysis:return-status-codes=False install code-analysis

...
[code-analysis-ci]
commands =
    ...
    {envbindir}/buildout -c {toxinidir}/{env:version_file} buildout:directory={toxinidir} code-analsysis:return-status-codes=True install code-analysis

...
```

and corresponding .travis.yml

```yaml

...
matrix:
    include:
        - python: "2.7"
env: TOXENV=docs,lint-py27,code-analysis-ci
...
```

**Comment by loechel** [comment]
the pre-commit hook could be disabled in plone.recipe.codeanalysis by setting 

```ini
...
pre-commit-hook = False
...
```

see https://pypi.python.org/pypi/plone.recipe.codeanalysis#supported-options
