### ISSUE TITLE
Add conditional test for content_type sub-template

### ISSUE THREAD

**Issue by MrTango** [plone/bobtemplates.plone#270]
To have a better test coverage we should add some more test to the content_type:

depending on what the developer has choosen in the mrbob questions, we should test:

- [x] check that the CT is globally addable, if dexterity_type_global_allow is True
- [x] check that the CT is not globally addable, if dexterity_type_global_allow is False
- [x] check that other CT could be added to the container, if dexterity_type_filter_content_types is False
- [x] check that no other CT could be added to the container, if dexterity_type_filter_content_types is True

These tests are added to the generated content_type, if the condition applies.

**Comment by mrsaicharan1** [comment]
- So my idea to increase the test coverage for this case is that we could check if assert if the object can be globally added when `dexterity_type_global_allow ` is `True`.
- After that, when `dexterity_type_filter_content_types` is set to False,then we could check if all the available content types can be added.  

-So the lines which I think should be add would look something like this :
`{{% if dexterity_type_global_allow %}}
        self.assertTrue(I{{{ dexterity_type_name_klass }}}.providedBy(obj).global_allow)
{{% if not dexterity_type_filter_types %}}
        self.assertTrue(IDexterityContainer.providedBy(obj))
        self.assertTrue(IArchetypesContainer.providedBy(obj))
        self.assertTrue(IPlonimoContainer.providedBy(obj))
{{% else %}}
        self.assertTrue(I{{{ dexterity_type_name_klass }}}.providedBy(obj))`

**Comment by mrsaicharan1** [comment]
@MrTango How do you think we could check that no other content_type can be added to container?
