### ISSUE TITLE
If global_allow is False, ask for parent containter content_type

### ISSUE THREAD

**Issue by MrTango** [plone/bobtemplates.plone#274]
If the user choose dexterity_type_global_allow: False we should ask for the conter content_type name we want to make the content type addable. This will allow us to configure the allowed_content_types setting in the FTI of the parent container content type and also generate working tests which uses the right container objects to create an content_type in. 

The mrbob question should named as follow:

`dexterity_parent_container_type_name`

**Comment by MrTango** [comment]
to create the parent container, we can use the constructContent method from portal_types tool, which ignores the FTI settings like global_allow:

```
portal_types = self.portal.portal_types
parent_id = portal_types.constructContent(
    'my_parent_container_type',
    self.portal,
    'parent_id',
    title='Parent container',
)
self.parent = self.portal[parent_id]
```

This way we only care about the settings of the CT we are currently checking.
To create the curent CT object, we are using the plone.api, which will also respect the settings for our CT.

**Comment by MrTango** [comment]
the settings global_allow and allowed_content_types are made in the FTI settings, which are defined in /profiles/default/types/<MyContenttype>.xml

**Comment by MrTango** [comment]
To update the xml file, you have to add a method like "_update_metadata_xml" but name it "_update_ct_types_fti_xml". in this method you add the curent CT name to the list of allowed_content_types

**Comment by MrTango** [comment]
set filter_content_types to True for the parent container, so that the parent container will actually filter the ctonent types which are alllowedf inside this container.

**Comment by MrTango** [comment]
I created a small issue #286 for the Item content type, so that we don't have the filter options for an Item.

**Comment by MrTango** [comment]
As discussed, we also need to update the robot test, depending on the global_allow and allowed_content_types settings. We need to use a Python based robot keyword, which will create the parent container, like we are doing in the unit tests already.

**Comment by kakshay21** [comment]
Closing it now. If I missed anything, we can reopen it
