### ISSUE TITLE
Add code-analysis to travis and fail the build on violations.

### ISSUE THREAD

**Issue by tisto** [plone/bobtemplates.plone#28]
I usually run code-analysis with plone.recipe.codeanalysis on travis as a first step. This way the build fails as early as possible on pep8 violations etc.. This might sound strict but 100% compliance with code-analysis is the only way to make it work in my experience. People can always remove that if they don't agree but I would consider that our best practice. Opinions?

Here is an example implementation:

https://github.com/plone/plone.restapi/blob/master/.travis.yml
https://github.com/plone/plone.restapi/blob/master/travis.cfg#L19

**Comment by pbauer** [comment]
+1

**Comment by gforcada** [comment]
:+1:

**Comment by cedricmessiant** [comment]
I agree too

**Comment by gil-cano** [comment]
+1

**Comment by gforcada** [comment]
That's already working like this for quite a long time.
