### ISSUE TITLE
Why is there a travis.cfg in the root dir but a jenkins.cfg in buildout.d Should this not be in the same place?

### ISSUE THREAD

**Issue by do3cc** [plone/bobtemplates.plone#3]

**Comment by tisto** [comment]
I don't think we should ship with jenkins.cfg at all. Travis should be the recommended way for add-on products.

**Comment by pbauer** [comment]
We test some client-specific addons on jenkins. For this a jenkins.cfg is usefull. I think we should keep it and maybe add a question to the setup "Prepare Jenkins Integration? [False]"

**Comment by do3cc** [comment]
There is a jenkins plugin to read .travis.yml file. I can investigate into how to use that and add documentation for it. the jenkins.cfg can die.

**Comment by cedricmessiant** [comment]
It could be great to have questions in the setup for both jenkins and Travis (Travis should be True by default).

**Comment by iham** [comment]
+1 on asking for preparation of ci-integration.

i like the idea of asking for support of one or even both (jenkins[false], travis[true])

personally i might end up using gitlabs ci so i dont want to use any of them. so this way its a simple input and not a search for files and configs to delete.

**Comment by gforcada** [comment]
There is no ``buildout.d`` anymore, so closing.
