### ISSUE TITLE
Too much pinnings in buildout.cfg?

### ISSUE THREAD

**Issue by idgserpro** [plone/bobtemplates.plone#301]
I've just created a package for a legacy system with Plone 4.3.9 with this package (I'm using plonecli 0.2.0 and bobtemplates.plone 3.3.0.)

Checking the generated `buildout.cfg`, I've seen that we have at least *40 packages pins*. Don't you think this is too much? Since they're said to be `# development dependencies (tools and pre commit hook)
**`, don't** we have a development.cfg effort like http://dist.plone.org/release/4.3-latest/versions.cfg for example? @esteele what do you think?

**Comment by jensens** [comment]
IMO it overrides too many packages. At least for Plone 5.1 this is not needed. It also adds headache when upgrading to a new Plone version (even if its just a bugfix release). The pins should be checked very carefully and there should be a reason noted as comment or as an `plone.versioncheck` compatible section entry.

**Comment by MrTango** [comment]
Help is very welcome ;)

**Comment by idgserpro** [comment]
@MrTango I've come to the conclusion that the way to go is pinning upstream. For example:

https://github.com/plone/Products.CMFPlone/issues/2867

When added upstream (and deciding what to do in https://github.com/plone/plonecli/issues/52) I think we can remove all the pinnings for 4.3.

So, I think this issue can be reopened.

> Help is very welcome ;)

I know. Since we can't sign the contributor's agreement for core plone packages, the help we can give is only opening issues.
