### ISSUE TITLE
Use a buildout recipe instead of an update.sh for translations?

### ISSUE THREAD

**Issue by idgserpro** [plone/bobtemplates.plone#306]
Instead of using a standalone [`update.sh`](https://github.com/plone/bobtemplates.plone/blob/350bffe80d046e2252c962e8b7a42236c655b043/bobtemplates/plone/addon/src/%2Bpackage.namespace%2B/%2Bpackage.name%2B/locales/update.sh.bob), what about using a recipe like it's used in [buildout.plonetest](https://github.com/collective/buildout.plonetest/blob/adb6b1346298900487d8672093dfa30aceb58bf3/qa.cfg#L72)?

What @mauritsvanrees (since you're a maintainer of buildout.plonetest) think about this?

**Comment by mauritsvanrees** [comment]
`buildout.plonetest` uses a recipe because it has to: it needs to get `${buildout:package-name}` from the buildout config.

In `bobtemplates.plone` we already know what the package name is, so we can just fill it in and generate the script.

So I don't see the need for a buildout recipe here.

**Comment by MrTango** [comment]
plonecli and bobtemplates.plone have now support for updating the locales.

**Comment by MrTango** [comment]
see https://github.com/plone/bobtemplates.plone/pull/304
