### ISSUE TITLE
bobtemplates.plone has no buildout.cfg

### ISSUE THREAD

**Issue by pbauer** [plone/bobtemplates.plone#338]
In cb1d3bd1f9be02cebd2f04215734aea2908ddc35 the `buildout.cfg` was removed my @loechel. Why? How would I start developing it? https://github.com/plone/bobtemplates.plone/blob/master/DEVELOP.rst still references a buildout.cfg, so the docs are broken.

**Comment by MrTango** [comment]
The docs are here: https://github.com/plone/bobtemplates.plone/blob/master/docs/develop.rst the DEVELOP.rst needs to be updated or deleted like @loechel started already.
