### ISSUE TITLE
README/Docs: best practice if possible

### ISSUE THREAD

**Issue by svx** [plone/bobtemplates.plone#34]
To include it better into docs.plone.org it would be better to follow http://docs.plone.org/about/documentation_styleguide_addons.html#id2 if that would be possible.
For now I have to copied it from hand, which we do not want to do, because we want to have up 2 date docs all the time.

**Comment by tisto** [comment]
You can remove the "if possible". We need to follow those best practices. It would be great if the docs team could review bobtemplates.plone as soon as it is ready.

Another related question: do we want to include sphinx docs in the buildout (by default, optional)?

**Comment by gforcada** [comment]
Why optional? I would say that a small docs/source/index.rst pulling CHANGES.rst and README.rst would not harm anyone, and thus, as they already follow best practices you paved the road for them to write docs and at the same time you encourage them to do so.

**Comment by do3cc** [comment]
I am worrysome about a default sphinx inclusion.
Pypi docs do not understand Sphinx, you cannot generate good sphinx docs that is than valid rst for pypi packages.

**Comment by gforcada** [comment]
@do3cc but on Pypi you only show long_description from setup.py, which basically always is README.rst + CHANGES.rst, so plain rst syntax without Sphinx extensions.

**Comment by do3cc** [comment]
My fear is that people start to add sphinx things to README.rst for the sphinx documentation. As it happened in plone.batching

**Comment by svx** [comment]
This is indeed a valid point, we tried to cover this here: http://docs.plone.org/about/documentation_styleguide_addons.html#id2 and here: http://docs.plone.org/about/documentation_styleguide_addons.html#id3, maybe we should make more clear what a README is and what you should **not** do in a README.

**Comment by do3cc** [comment]
svx Thanks for the pointers!

**Comment by tisto** [comment]
@do3cc You made a valid point. I'd be ok with not having sphinx by default. It might be overkill for most packages.

**Comment by do3cc** [comment]
I am not convinced myself. See also my (failing) PR:
https://github.com/plone/bobtemplates.plone/pull/48
It is possible to add a warning that is invisible in most renderings

**Comment by do3cc** [comment]
I mean, I am not convinced myself that adding sphinx is bad. You can always delete it anyway

**Comment by svx** [comment]
+1 I think a good readme will be enough in most cases, but we should make sure that we provide good information about that, and also point ppl to out styleguide.

Which brings me back to reason why I opened this ticket :), can we try to follow the best practices aka style guide with this repo too ?
http://docs.plone.org/about/documentation_styleguide_addons.html#id2

**Comment by do3cc** [comment]
I am not sure, what fails at travis...

**Comment by gforcada** [comment]
I took a look at the styleguide http://docs.plone.org/about/documentation_styleguide.html and after moving LICENSE.rst and LICENSE.GPL into top level folder I think we are good to go.

Closing, reopen if you disagree.
