### ISSUE TITLE
test_setup not passing for Plone 5.1

### ISSUE THREAD

**Issue by thet** [plone/bobtemplates.plone#342]
Since Plone 5.1 there was a refactoring of the installer logic. We cannot use portal_quickinstaller tools to check if a products is installed or not but the profile registry. See:

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/controlpanel/browser/quickinstaller.py#L51 u.a.

These generated tests break:
https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone/addon/src/%2Bpackage.namespace%2B/%2Bpackage.name%2B/tests/test_setup.py.bob

**Comment by MrTango** [comment]
should be addressed be #344, I'll work on that PR and merge it when it's ready.

**Comment by MrTango** [comment]
should be fixed now, as the PR is merged.
I was wondering why we didn't see the build failing then.
As the skeleton test are running also on 5.1 the generated tests for a package.
