### ISSUE TITLE
requirements.txt should point to dist

### ISSUE THREAD

**Issue by jensens** [plone/bobtemplates.plone#346]
https://github.com/plone/bobtemplates.plone/blob/master/requirements.txt should point in Plone 5.1 to
```
-r http://dist.plone.org/release/5.1.4/requirements.txt
```

**Comment by MrTango** [comment]
Why? bobtemplates.plone has no dependencies to Plone, it can in fact have other dependencies than Plone.

**Comment by jensens** [comment]
well, I took the wrong one, I mean this one
https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone/buildout/requirements.txt
or this
https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone/addon/requirements.txt
etc.
