### ISSUE TITLE
views theme directory

### ISSUE THREAD

**Issue by serg-quinta** [plone/bobtemplates.plone#353]
I made previous theme with bobtemplates.plone v3.4.2 and I use views folder to add new templates. Now I updated bobtemplates.plone to 3.5.2, created new theme and copied templates from previous theme but I got an error. I noticed that there is no plone.app.themingplugins in requires.

I think it'd be useful to delete views folder because there is no plone.app.themingplugins and add fragments folder because there is collective.themefragments.

It would be really helpful to do this and update documentation.

**Comment by MrTango** [comment]
The requirements are added by the theme sub-templates like the "theme" sub-template. If you create an add-on package and then add a theme, it should update your setup.py with the requirments. You need to run builout of course after.  If there is still no added requirements please check if you have the placeholder string in that list or look for warning when you add the theme.

**Comment by serg-quinta** [comment]
@MrTango Hello. Thank you for your reply.
I have next code in setup.py:

`    install_requires=[
        # -*- Extra requirements: -*-
        'collective.themefragments',
        'collective.themesitesetup',
        'plone.api>=1.8.4',
        'Products.GenericSetup>=1.8.2',
        'setuptools',
        'z3c.jbot',
    ],`

There is no plone.app.themingplugins package in the install_requires
