### ISSUE TITLE
Support adding upgrade steps

### ISSUE THREAD

**Issue by ericof** [plone/bobtemplates.plone#370]
bobtemplates.plone could support adding an upgrade step to an existing package.

[Example of Upgrade steps](https://github.com/plonegovbr/brasil.gov.portal/tree/master/src/brasil/gov/portal/upgrades)
[Example of tests for upgrade steps](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/tests/test_upgrades.py)

**Comment by MrTango** [comment]
[Plone upgrade steps.pdf](https://github.com/plone/bobtemplates.plone/files/3081328/Plone.upgrade.steps.pdf)

**Comment by tobiasherp** [comment]
**Caution** - when I first clicked on that `Plone upgrade steps.pdf` link, it froze my Firefox browser ...

**Comment by MrTango** [comment]
it's just a pdf file, no problem with FF under Linux on my side.
These are just some notes from the sprint where we had the idea of this template.

**Comment by MrTango** [comment]
The structure will be as follow:

- upgrades
  - v20190314_00
  - v20190314_01
  - v20190903_00
    - profile/[*].xml  (contains GS profile files for the upgrade steps)
    - __init__.py  (contains python handler for upgrade steps)
    - configure.zcml  (contains the upgrade steps registrations for this version)
  - __init__.py
  - configure.zcml  (includes the modules (versions) like: v20190314_00)
