### ISSUE TITLE
Plone 4 template `theme` creates a reference to /++theme++my-theme/++theme++barceloneta/backend.xml which doesn't exist

### ISSUE THREAD

**Issue by idgserpro** [plone/bobtemplates.plone#380]
I'm assuming it was supposed to work on Plone 4.3, based on this commit https://github.com/plone/bobtemplates.plone/commit/b5b60d677fb777631a6ac6fa6dc46e34a1d20a16 and from official docs in https://github.com/plone/bobtemplates.plone#compatibility:

> Remove version conditions for addon dependencies, p43-p52 should be supported. This is makes sense, because the generated package **should be useable for Plone version from 4.3 until current**. If someone wants to drop support, she can remove some of the dependencies, as 
they are in Plone core in newer versions.

But when I create an addon using `plonecli create addon my.addon` and add a theme to it (since `theme_package` is deprecated), I get this traceback:

```
Traceback (most recent call last):
  File "/home/user/.buildout/eggs/plone.subrequest-1.8.5-py2.7.egg/plone/subrequest/__init__.py", line 146, in subrequest
    traversed = request.traverse(path)
  File "/home/user/.buildout/eggs/Zope2-2.13.28-py2.7.egg/ZPublisher/BaseRequest.py", line 508, in traverse
    subobject = self.traverseName(object, entry_name)
  File "/home/user/.buildout/eggs/Zope2-2.13.28-py2.7.egg/ZPublisher/BaseRequest.py", line 332, in traverseName
    ob2 = namespaceLookup(ns, nm, ob, self)
  File "/home/user/.buildout/eggs/zope.traversing-3.13.2-py2.7.egg/zope/traversing/namespace.py", line 112, in namespaceLookup
    return traverser.traverse(name, ())
  File "/home/user/.buildout/eggs/plone.resource-1.2.3-py2.7.egg/plone/resource/traversal.py", line 27, in traverse
    raise NotFound
NotFound
```

Plone barceloneta is a Plone 5 theme, and comes as default in the installation, so the include directive would work if I was using Plone 5. But in Plone 4 how should we handle this? Just remove the directive? Is the new `theme` template really compatible with Plone 4, or are we stick with the deprecated `theme_package`?

Creating with `theme_package` in a Plone 4 installation this is the result:

![Seleção_170](https://user-images.githubusercontent.com/8203476/57874134-47112480-77e6-11e9-9c5c-b174f578d7bd.png)

Is barceloneta in bobtemplates.plone really compatible with Plone 4, or should I just use the *skeleton* in `theme` folder created from bobtemplates.plone to implement my own?

@erral 

Using older versions of plonecli and bobtemplates.plone (Add to requirements.txt and use 'pipenv install --skip-lock -r requirements.txt`) gives the same behavior:

```shell
# https://github.com/plone/plonecli/blob/0.2.0/setup.py#L28
plonecli==0.2.0
# https://github.com/plone/bobtemplates.plone/blob/master/CHANGES.rst#342-2018-08-13
bobtemplates.plone==3.4.2
```

@fredvd you refreshed backend.xml in the past in https://github.com/plone/bobtemplates.plone/commit/f85dad913837e1dc7c66c963f5715afda5ddc8ea. Did it work before, or it always had this layout just to be used as a foundation for a specific theme?

**Comment by erral** [comment]
Disclaimer: I have never used the 'theme' subtemplate in Plone 4.

As far as I can see the 'theme' subtemplate uses some Plone 5 options in the manifest.cfg file such as development-css or development-js and so on:

https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone/theme/theme/manifest.cfg.bob

So I guess that to make the theme work on Plone 4 you would need to remove that (completely untested on my side).

Regarding other templates, we are successfully using the 'addon' template with 'content_type', 'vocabulary', 'behavior' and 'viewlet' subtemplates in Plone 4.

**Comment by MrTango** [comment]
I agree and i updated the readme to make that clear.
The theme templates are bedfault for Plone > 5 only.
With little efford you can still use them for Plone 4.
The sub-template "theme" is very simple but uses the backend rules from barceloneta be default.
The other sub-template are all meant to work on plone >= 4.3.

**Comment by idgserpro** [comment]
> I agree and i updated the readme to make that clear. The theme templates are bedfault for Plone > 5 only.

Thank you. Do you think it's better do adapt a `theme` subtemplate to use in Plone 4, or use the deprecated `theme_package`? In the deprecated `theme_package` is not optimal but it doesn't give the error.

**Comment by MrTango** [comment]
just use the old theme package if you don't need the theme inside existing addons together with other functionallity. But in the end it's up to you. You can always replace whats in side the theme folder with an old Plone 4 based Diazo theme.
