### ISSUE TITLE
Disabling GIT support should, avoid git questions in subtemplate

### ISSUE THREAD

**Issue by idgserpro** [plone/bobtemplates.plone#382]
This is similar to https://github.com/plone/bobtemplates.plone/issues/300, but when trying to add a theme to a package with `git_init = n`:

```
Using plone_theme template:
Should we run?:
git add .
git commit -m "Add theme: dgdfge"
in: /tmp/my.theme
[y]/n:
```

**Comment by MrTango** [comment]
git_init is not to disable GIT but to not initialize a repository.
This is usefull if your package lives in a project repository and you don't want seperate repositories for every package.

**Comment by MrTango** [comment]
But you can disable git entirely if thats what you want.

**Comment by MrTango** [comment]
Alos note that you can answer the question also in your users mrbob config file.
Questions answered there will not be ask again.
But you can also just chnage the defaults and keep the questions.

**Comment by idgserpro** [comment]
> git_init is not to disable GIT but to not initialize a repository. This is usefull if your package lives in a project repository and you don't want seperate repositories for every package.

Thanks for the explanation.

> But you can disable git entirely if thats what you want.

Which option is that? I already have:

```
package.git.init = False
package.git.autocommit = False
```

> Also note that you can answer the questions also in your users mrbob config file.

How do I know which questions and answers can I put in my mrbob file? For the situation described in this issue for example, I can relate to the code in https://github.com/plone/bobtemplates.plone/blob/da6a8fb6567bfa3da47366ce652b10f9bf71c362/bobtemplates/plone/base.py#L142 but don't know exactly what should I put in my mrbob.ini file to disable git message for a subtemplate.
