### ISSUE TITLE
Drop locales question.

### ISSUE THREAD

**Issue by tisto** [plone/bobtemplates.plone#42]
Locales should be considered best practice. Even if they are not used. I would drop this question and always include a locales folder.

Opinions?

**Comment by do3cc** [comment]
:+1: and scripts to allow easy updating and easy testing if po files are up to date

**Comment by gforcada** [comment]
:+1:  with @do3cc additions

**Comment by tisto** [comment]
I'm +1 on adding those scripts. Though, we should open a new issue.
