### ISSUE TITLE
Use same version of coverage in createcoverage and coveralls

### ISSUE THREAD

**Issue by idgserpro** [plone/bobtemplates.plone#421]
[createcoverage](https://github.com/plone/bobtemplates.plone/blob/0b86c3771dd9d7aa9d253fa9ec1fa07f5254d193/bobtemplates/plone/addon/base.cfg.bob#L73)  uses the version of coverage pinned in the buildout. [coveralls](https://github.com/plone/bobtemplates.plone/blob/4a792eb0899317e406310661eee5b55d40a5d915/bobtemplates/plone/theme_package/.travis.yml.bob#L29) uses the [latest version](https://github.com/plone/bobtemplates.plone/blob/4a792eb0899317e406310661eee5b55d40a5d915/bobtemplates/plone/theme_package/.travis.yml.bob#L26). These versions are incompatible.  Perhaps it's best install coverage with buildout instead of pip.

**Comment by idgserpro** [comment]
Here is an example of the issue:

https://travis-ci.com/collective/collective.restapi.pfg/jobs/283775427#L1602

@erral FYI

**Comment by erral** [comment]
I have fixed it in that package pinning coverage<5 when doing pip install. See https://github.com/collective/collective.restapi.pfg/blob/master/.travis.yml#L34
