### ISSUE TITLE
Error running test on gitlab with python27

### ISSUE THREAD

**Issue by cekk** [plone/bobtemplates.plone#428]
Hi,
using the generated configuration (.gitlab-ci.yml) i have problems running tests for Plone 51 and 52 with python27 (using a python:37-stretch image everything works fine).

I tried to reproduce the error here: https://gitlab.com/cekk/example.package/-/jobs/479479660

Buildout ends without errors, but when i launch test script, i have this error:

    DistributionNotFound: The 'Zope2' distribution was not found and is required by the application

Obviously locally i don't have errors. My guess is something wrong with the linux image/distro, but i can't figure it out.

Any ideas?

**Comment by MrTango** [comment]
Hi the gitlab config is curently a bit out of sync, feel free to update it acording to the travis config.
