### ISSUE TITLE
Should behavior zcml include 'for' element?

### ISSUE THREAD

**Issue by mtrebron** [plone/bobtemplates.plone#431]
The zcml configuration created in  https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone/behavior.py#L67 does not currently specify for which interfaces the behavior applies. 

This causes an error ['The factory can not be declared as multi-adapter.'](https://github.com/plone/plone.behavior/blob/master/plone/behavior/metaconfigure.py#L89) at startup when the behavior factory is defined as a multiadapter. Would it be wise to include a general default (e.g. `plone.dexterity.interfaces.IDexterityContent`) here?

**Comment by jensens** [comment]
For schema only behaviors `for` is not needed and a warning would be issued if given.

**Comment by MrTango** [comment]
sorry for the late answer, if there is a use case where we should handle things differently, please describe it, we can always make the template more flexible and cover multiple variations.

**Comment by mtrebron** [comment]
In hindsight, my issue does not seem to be related to bobtemplates.plone. The use case was to add either IImage or ILeadImage interfaces to particular instances of a content type via a behavior. However, I later found that plone.behavior does not support this. The intended result was eventually achieved by creating subscribers for IObjectAddedEvent and IObjectModifiedEvent.
