### ISSUE TITLE
[buildout] index URL is outdated

### ISSUE THREAD

**Issue by ale-rt** [plone/bobtemplates.plone#436]
See https://github.com/plone/bobtemplates.plone/blob/0b86c3771dd9d7aa9d253fa9ec1fa07f5254d193/bobtemplates/plone/addon/base.cfg.bob#L6

Better would be nothing or at least for really really old buildout versions (i.e. not in base.cfg).

**Comment by idgserpro** [comment]
@ale-rt this can be done at `buildout.plonetest` as well:

https://github.com/collective/buildout.plonetest/blob/master/plone-5.2.x.cfg#L2

**Comment by MrTango** [comment]
fixed in 5.1.1

**Comment by idgserpro** [comment]
@MrTango I think that for the version of the buildout used in Plone 4.3, it will be necessary to have the index. But I think it won't be a problem because it extends from `buildout.plonetest`. And there we have the index.
