### ISSUE TITLE
Fix .gititgnore

### ISSUE THREAD

**Issue by ale-rt** [plone/bobtemplates.plone#437]
Looking at 
https://github.com/plone/bobtemplates.plone/blob/50e415989fdd59b136c20502377ce2d8741745d7/bobtemplates/plone/addon/.gitignore.bob it seems to me that everybody was throwing there every possible immaginable string.

I would remove
https://github.com/plone/bobtemplates.plone/blob/50e415989fdd59b136c20502377ce2d8741745d7/bobtemplates/plone/addon/.gitignore.bob#L18
and 
https://github.com/plone/bobtemplates.plone/blob/50e415989fdd59b136c20502377ce2d8741745d7/bobtemplates/plone/addon/.gitignore.bob#L33-L40
al together for a start.

**Comment by MrTango** [comment]
makes sense to me.

**Comment by MrTango** [comment]
fixed
