### ISSUE TITLE
Write proper unit tests, aim for 100% unit test coverage.

### ISSUE THREAD

**Issue by tisto** [plone/bobtemplates.plone#44]
https://github.com/plone/bobtemplates.plone/blob/master/tests.py is a good start, but we are far away from testing every possible combination of questions. 

We already have functional acceptance tests for the main package types (regular, nested, in the future: theme, dexterity), which are the most important tests in my opinion.

Nonetheless, I think we should aim for 100% test coverage (for just unit tests) as well. Acceptance test coverage should not count. First step would be to refactor tests.py to not rely on external question.ini files. It is also essential to keep things simple, otherwise we will not be able to reach 100% test coverage with reasonable effort.

**Comment by MrTango** [comment]
We have already nearly 100% coverage for the generated test.
And we are working hard to increase the coverage of the package-test as well.
I'll add this to the list of GSoC, as we will increase the coverage there too.
