### ISSUE TITLE
isort5 - remove option in setup.cfg.bob

### ISSUE THREAD

**Issue by 1letter** [plone/bobtemplates.plone#448]
see [isort upgrade](https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/#not_skip)
remove option `not_skip =  __init__.py` in [setup.cfg.bob](https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone/addon/setup.cfg.bob#L17)

**Comment by wesleybl** [comment]
@1letter `isort` >= 5.0.0 is not compatible with Python 2. See:

https://github.com/PyCQA/isort/blob/f6f825ec848693cfbdd7b9d6210c4284905d5d67/pyproject.toml#L27

So, I think this option is still necessary for Python 2, which should use `isort` < 5.0.0. What can be done is to put a BBB comment on it.

**Comment by MrTango** [comment]
Fee free to PR a comment or DOC, for now we should leave it as it is.
I had the same idea a while ago, but without dropping support for Python2 we can't switch.
It would be possible though to create a different configuration, if Python2 support can be disabled for specific add-on's.
I don't have time to work on this right now, but I can help if someone want's to work on a PR to make this configurable in the addon template.
