### ISSUE TITLE
virtualenv --clear removes all files

### ISSUE THREAD

**Issue by frisi** [plone/bobtemplates.plone#464]
the [developer readme](https://github.com/plone/bobtemplates.plone/blob/5.2.0/bobtemplates/plone/addon/DEVELOP.rst) states that the virualenv should be boostrapped with `$ virtualenv --clear .`

on my machine both of the below commands empty the complete current directory (the addon package i'm supposed to work on)

```
$ virtualenv --clear .

$ python3.8 -m venv --clear
```

the docs should either put the virtualenv in a subdirectory

```
python3 -m venv v
```

or selectively delete the files

```
rm -rf bin/python* bin/pip bin/activate* local/ include/ lib/ bin/buildout bin/easy_install bin/pip*
```

**Comment by ale-rt** [comment]
I started the habit of having the virtualenv in a separate folder for this same exact reason (the new virtualenv is a killer).

**Comment by MrTango** [comment]
plonecli does this in a separate folder since 2.x which avaoids this, but you have a point the docs need an update there too.
Please help with a PR, I have already a lot on my plate.

**Comment by MrTango** [comment]
python3 -m venv venv 
is what `plonecli build` does

**Comment by MrTango** [comment]
fixed and released, if you find anything else left, I'm happy with a direct PR.
