### ISSUE TITLE
update barceloneta_theme version

### ISSUE THREAD

**Issue by me-kell** [plone/bobtemplates.plone#514]
`bobtemplates.plone 6.0b13` uses `plonetheme.barceloneta 3.0.0-alpha.7`

Themes created with `bobtemplates.plone 6.0b13` and installed in Plone `6.0.0b1` show some problems: e.g. global sections are not working properly.

The current version of `plonetheme.barceloneta` is `3.0.0-beta2` has substantial changes since version `3.0.0-alpha.7`:

- Bootstrap 5.1.3 -> 5.2.0
- substantial changes in `index.html` and `rules.xml` files
- substantial changes in `*.scss` files

**Comment by me-kell** [comment]
Meanwhile `plonetheme.barceloneta` is `3.0.0-beta5`.

**Comment by MrTango** [comment]
solved in 6.0.0b14
