### ISSUE TITLE
z3c.autoinclude dependency is missing

### ISSUE THREAD

**Issue by do3cc** [plone/bobtemplates.plone#52]
Or is there a good reason to leave it out?

**Comment by tisto** [comment]
You mean this? https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone_addon/src/%2Bpackage.namespace%2B/%2Bpackage.name%2B/configure.zcml.bob#L11

Or do you want to explicitly declare this dependency?

**Comment by do3cc** [comment]
I mean the explicit dependency in setup.py requires

**Comment by jensens** [comment]
this is a dependency of plone anyway, well, we may declare it, but it may also cause confusion.

**Comment by iham** [comment]
@jensens thanks for pointing that out. i thought, z3c.autoinclude has to be in every package as a "hook" to make it "visible".
