### ISSUE TITLE
Fresh templates have outdated pyc files

### ISSUE THREAD

**Issue by do3cc** [plone/bobtemplates.plone#53]
I've created a template viewout a sample view and now the package contains a view.pyc without a view.py

**Comment by tisto** [comment]
I think we should rewrite the view part from the scratch and integrate it into the dexterity example.

**Comment by djowett** [comment]
@tisto, not sure about that I don't think views are exclusive to dexterity.

**Comment by tisto** [comment]
@djowett they are of course not. Though, as said before, we have to reduce complexity to make things manageable and testable. We should try not to repeat the mistakes we made with ZopeSkel/Templer and learn from our past experiences.

**Comment by do3cc** [comment]
I can imagine lots of scenarios where I have an egg not containing a view, and I believe that there are few packages with a view but not a content type. From my side, a view is not necessary if there is no content type

**Comment by pbauer** [comment]
the .pyc probably results in the fact that mr.bob does not delete a existing package when creating one with the same name (but different options). The view has been removed anyway.
