### ISSUE TITLE
Clarification: `theme` - `theme_barceloneta` - `theme_basic`

### ISSUE THREAD

**Issue by petschki** [plone/bobtemplates.plone#551]
I fixed an issue with latest barceloneta and bootstrap 5.3 and came accross those three theming templates. All define `@plone/plonetheme-barceloneta-base` as (dev)dependency ... can anyone clarify the purpose of each?

/cc @santonelli @MrTango

**Comment by MrTango** [comment]
theme: Diazo based theme which only uses parts scss from barcelonata and it's meant to build themes not related to Barceloneta.

theme_barcelonata: is like a copy a barceloneta which one can customize then.

the third version is meant for building a theme without any Diazo, just by overriding templates. like the tokyo theme does.

**Comment by MrTango** [comment]
`@plone/plonetheme-barceloneta-base` is used by all of them to include and reuse parts of the default theme or at least some variables.
