### ISSUE TITLE
4.3.4 is not a valid trove classifier

### ISSUE THREAD

**Issue by tomgross** [plone/bobtemplates.plone#56]
With the default options bobtemplates.plone creates a setup.py with the following classifiers:
```python
    # Get more from http://pypi.python.org/pypi?%3Aaction=list_classifiers
    classifiers=[
        "Environment :: Web Environment",
        "Framework :: Plone",
        "Framework :: Plone :: 4.3.4",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2.7",
    ],
```
According to the cited list
4.3.4 is not valid but 4.3 is:

```
Framework :: Plone
Framework :: Plone :: 3.2
Framework :: Plone :: 3.3
Framework :: Plone :: 4.0
Framework :: Plone :: 4.1
Framework :: Plone :: 4.2
Framework :: Plone :: 4.3
Framework :: Plone :: 5.0
```

**Comment by aclark4life** [comment]
Right. No need to get that specific with the classifiers and ``Framework :: Plone :: 4.3.4`` may be ignored by PyPI when comparing to ``"Framework :: Plone :: 4.3``.

**Comment by tisto** [comment]
+1 for fixing that. I think right now the "plone.version" answer is taken.
