### ISSUE TITLE
Script should expose package type options

### ISSUE THREAD

**Issue by tomgross** [plone/bobtemplates.plone#57]
It would be nice if the script would expose the package type options: *Basic*, *Dexterity*, *Theme*

**Comment by frisi** [comment]
@tomgross: this has been *heavily* discussed in #46 already.

**Comment by tomgross** [comment]
@frisi I'm not sure if this is the same thing. As a User of the templates I want to *see directly* which options I have. Now it is like ordering without the menu.

**Comment by frisi** [comment]
sorry tom, i misunderstood this completely. thought these options are not available anymore - but that's not the case ;-)

**Comment by tisto** [comment]
Here is what we have right now:

What kind of package would you like to create? Choose between 'Basic', 'Dexterity', and 'Theme'. [Basic]

I would like to be more explicit and use a description with multiple lines. Though, mr.bob currently does not support this.

@tomgross what kind of solution do you have in mind?

**Comment by tomgross** [comment]
The second sentence "Choose between ... " is missing in the latest released
version. That was what I thought of in the first place.
Timo Stollenwerk <notifications@github.com> schrieb am Di., 14. Apr. 2015
um 07:30:
