### ISSUE TITLE
travis build status is unknown

### ISSUE THREAD

**Issue by pbauer** [plone/bobtemplates.plone#63]
What went wrong here? See https://travis-ci.org/plone/bobtemplates.plone

**Comment by tisto** [comment]
I think the travis web gui has issues...

**Comment by tisto** [comment]
bobtemplates.plone was disabled on travis. no idea why...

**Comment by tisto** [comment]
Build is green: https://travis-ci.org/plone/bobtemplates.plone/builds/66748245
