### ISSUE TITLE
Cannot build templates on windows: Error: "C:\Plone42\src\test.test" is not a valid packagename.

### ISSUE THREAD

**Issue by wirthual** [plone/bobtemplates.plone#72]
Hello,

i always get this error: 
Error: 'C:\Plone42\src\test.test' is not a valid packagename.

I assume its because of this check:
validate_packagename(configurator):

**Comment by pbauer** [comment]
@wirthual I guess nobody ever tried to use it with windows. 

    configurator.target_directory.split('/')[-1]

will not work on windows. A pull-request to adress that would be welcome.

**Comment by jensens** [comment]
here python std lib has an answer:
https://docs.python.org/2/library/os.path.html#os.path.split

**Comment by pbauer** [comment]
fixed in https://github.com/plone/bobtemplates.plone/commit/470b4fa470b41730ea3fb0d51f05ace8b4c32ab2
