### ISSUE TITLE
package.dexterity_type_name question doesn't sanitize answer

### ISSUE THREAD

**Issue by djowett** [plone/bobtemplates.plone#76]
For example it doesn't remove spaces...

So if I add e.g. "Banner Slide" or "News Item" then my imports will look like this:

     from another.product.interfaces import IBanner Slide
     from another.product.interfaces import INews Item

**Comment by pbauer** [comment]
Fixed in documentation: https://github.com/plone/bobtemplates.plone/commit/494dce040662fbfb80ab832fb749d8980f8d775d

**Comment by djowett** [comment]
That's great - thanks
