### ISSUE TITLE
Does not deal well when creating Dexterity content types with two words

### ISSUE THREAD

**Issue by pigeonflight** [plone/bobtemplates.plone#81]
How to replicate this issue.

Create a new package using mr.bob, when asked select "Dexterity" then name the content type something like "Car Part".

After adding it to you buildout and relaunching Plone you'll get an error like this:

     SyntaxError: invalid syntax (interfaces.py, line 14)

You will see that interfaces.py contains a class with a space in it (ICar Part) in this case, which is not valid for Python.

**Comment by davilima6** [comment]
If content type is named "Car part", shouldn't we also CamelCase All Words? Or too much magic?

**Comment by tisto** [comment]
@davilima6 I think we should at least make sure the type name starts with an upper case letter "car part" -> "Carpart". I guess we could enforce camel case but we would need proper testing for that because I could imagine a few edge cases.

**Comment by faustram** [comment]
I'm sorry. 
I had a similar error like @pigeonflight. 
I named my add-on "PFinance.SingleMovement" and in interfaces.py, row14 I have:
"class IPFinance.SingleMovement(Interface):"
So "bin/instance fg" fail.

**Comment by pbauer** [comment]
@faustram the Content type name should not contain space, dot, minus or special characters. We could add a check regex to check for valid names. See https://github.com/plone/bobtemplates.plone/pull/112
